name: Lint next-version tags

on:
  pull_request:

jobs:
  next-version-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Check $$next-version$$ usage in added lines
        run: bash scripts/check-next-version-tag.sh "${{ github.event.pull_request.base.sha }}"
