name: Linting

on:
  pull_request:
  push:
    branches: [trunk]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none
      - run: composer install --no-progress
      - run: vendor/bin/phpcs
